config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :todos, only: %i[index show] do
    resources :tasks, only: %i[create]
    delete 'uncompleted', to: 'tasks#destroy'
  end
  root 'todos#index'
end


  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
  has_many :todos, through: :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    todo = Todo.find(params[:todo_id])
    task = Task.new(
      user: current_user,
      todo: todo,
      completed: true
    )
    if task.save
      redirect_to todos_path, notice: 'Has completado tu tarea !'
    else
      redirect_to todos_path, alert: 'Error al completar tu tarea :C'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to todos_path, notice: 'Ya no has completado la tarea'
  end
  
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!, only: :show
  def index
    @todos = Todo.all
    @tasks = Task.all
    #@uncompleted_tasks = current_user.tasks.where(completed: false)
  end

  def show
    @todo = Todo.find(params[:id])
    @tasks = Task.where(todo: @todo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba4RailsNanMati</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% if notice.present? %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path%>">Tareas para el 18</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <% if user_signed_in? %>
          <p class="nav-item nav-link">Tareas completadas: <%= current_user.tasks.count %> </p>
          
        <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class:'nav-item nav-link' %>
      <% else %>
        <a class="nav-item nav-link" href="<%= new_user_session_path%>">Iniciar sesión</a>
        <a class="nav-item nav-link" href="<%= new_user_registration_path%>">Registrarse</a>
      <% end %>
      
    </div>
  </div>
</nav>

app/views/tasks/my_tasks.html.erb
<h1>Tareas que has completado:</h1>
<br>
<div class="row">
  <% @my_tasks.each do |task| %>
    <div class="col-sm-2"><strong><%= task.todo.name %></strong></div>
    <div class="col-sm-6"><%= image_tag task.todo.image %></div>
    <div class="col-sm-4"><%= link_to 'No completé esta tarea', task_path(task), method: :delete, class:'btn btn-danger'%></div>
  <% end %>
</div>
  

app/views/todos/index.html.erb
<h1>Lista de tareas !</h1>

<div class="row">
  <% @todos.each do |todo| %>
    <div class="card col-sm-4 text-center pt-3">
      <%= image_tag todo.image,class:'card-img-top img-fluid' %>
      <div class="card-body">
        <h5 class="card-title"><%= todo.name %></h5>
        <%= link_to 'Ver detalle', todo, class:'btn btn-primary btn-sm'%>
          
            <% if todo.users.include? current_user %>
              <%= link_to todo_uncompleted_path(todo), method: :delete, class:'btn btn-danger btn-sm' do %>
                <i class="fas fa-times"></i>
              <% end %>
            <% else %>
              <%= link_to todo_tasks_path(todo), method: :post, class:'btn btn-success btn-sm' do %>
                <i class="fas fa-check"></i>
              <% end %>
            <% end %>      
          
      </div>
    </div>
  <% end %>
</div>

app/views/todos/show.html.erb
<p><strong>Tarea:</strong> <%= @todo.name %></p>

<p><strong>Imágen:</strong></p>
<p><%= image_tag @todo.image %></p>

<h1>Personas que han completado esta tarea:</h1>

<hr>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.user.email %></li>
  <% end %>
</ul>

<%= link_to 'Volver a las tareas', todos_path, class:'btn btn-primary' %>